services:
  rva_ux_hub_frontend:
    container_name: rva_ux_hub_frontend
    build:
      context: /opt/rva/modulos/rva_ux_hub
      dockerfile: containers/nextjs/Dockerfile
    ports:
      - "3080:3080"
    restart: unless-stopped
